swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: swagger-tutorial-drcalx.c9users.io:8081
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /single:
    x-swagger-router-controller: single
    get:
      description: Gets the singles list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetSinglesListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetSinglesListResponse:
    required:
      - singles
    properties:
      singles:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            artist:
              type: string
            year:
              type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
